# Generated by Django 4.0.2 on 2022-02-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oreder_detail',
            new_name='Order_detail',
        ),
    ]
